export function Home() {
  return (
    <pre>
      <code>{`

                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                
EEEEEEEEEEEEEEEEEEEEEE                          tttt         hhhhhhh                                                                                                                     tttt                                                                                                 !!! 
E::::::::::::::::::::E                       ttt:::t         h:::::h                                                                                                                  ttt:::t                                                                                                !!:!!
E::::::::::::::::::::E                       t:::::t         h:::::h                                                                                                                  t:::::t                                                                                                !:::!
EE::::::EEEEEEEEE::::E                       t:::::t         h:::::h                                                                                                                  t:::::t                                                                                                !:::!
  E:::::E       EEEEEE    ssssssssss   ttttttt:::::ttttttt    h::::h hhhhh           eeeeeeeeeeee    rrrrr   rrrrrrrrr                   eeeeeeeeeeee    uuuuuu    uuuuuu       ttttttt:::::ttttttt        eeeeeeeeeeee           aaaaaaaaaaaaa      mmmmmmm    mmmmmmm      ooooooooooo     !:::!
  E:::::E               ss::::::::::s  t:::::::::::::::::t    h::::hh:::::hhh      ee::::::::::::ee  r::::rrr:::::::::r                ee::::::::::::ee  u::::u    u::::u       t:::::::::::::::::t      ee::::::::::::ee         a::::::::::::a   mm:::::::m  m:::::::mm  oo:::::::::::oo   !:::!
  E::::::EEEEEEEEEE   ss:::::::::::::s t:::::::::::::::::t    h::::::::::::::hh   e::::::eeeee:::::eer:::::::::::::::::r              e::::::eeeee:::::eeu::::u    u::::u       t:::::::::::::::::t     e::::::eeeee:::::ee       aaaaaaaaa:::::a m::::::::::mm::::::::::mo:::::::::::::::o  !:::!
  E:::::::::::::::E   s::::::ssss:::::stttttt:::::::tttttt    h:::::::hhh::::::h e::::::e     e:::::err::::::rrrrr::::::r            e::::::e     e:::::eu::::u    u::::u       tttttt:::::::tttttt    e::::::e     e:::::e                a::::a m::::::::::::::::::::::mo:::::ooooo:::::o  !:::!
  E:::::::::::::::E    s:::::s  ssssss       t:::::t          h::::::h   h::::::he:::::::eeeee::::::e r:::::r     r:::::r            e:::::::eeeee::::::eu::::u    u::::u             t:::::t          e:::::::eeeee::::::e         aaaaaaa:::::a m:::::mmm::::::mmm:::::mo::::o     o::::o  !:::!
  E::::::EEEEEEEEEE      s::::::s            t:::::t          h:::::h     h:::::he:::::::::::::::::e  r:::::r     rrrrrrr            e:::::::::::::::::e u::::u    u::::u             t:::::t          e:::::::::::::::::e        aa::::::::::::a m::::m   m::::m   m::::mo::::o     o::::o  !:::!
  E:::::E                   s::::::s         t:::::t          h:::::h     h:::::he::::::eeeeeeeeeee   r:::::r                        e::::::eeeeeeeeeee  u::::u    u::::u             t:::::t          e::::::eeeeeeeeeee        a::::aaaa::::::a m::::m   m::::m   m::::mo::::o     o::::o  !!:!!
  E:::::E       EEEEEEssssss   s:::::s       t:::::t    tttttth:::::h     h:::::he:::::::e            r:::::r                        e:::::::e           u:::::uuuu:::::u             t:::::t    tttttte:::::::e                a::::a    a:::::a m::::m   m::::m   m::::mo::::o     o::::o   !!! 
EE::::::EEEEEEEE:::::Es:::::ssss::::::s      t::::::tttt:::::th:::::h     h:::::he::::::::e           r:::::r             ,,,,,,     e::::::::e          u:::::::::::::::uu           t::::::tttt:::::te::::::::e               a::::a    a:::::a m::::m   m::::m   m::::mo:::::ooooo:::::o       
E::::::::::::::::::::Es::::::::::::::s       tt::::::::::::::th:::::h     h:::::h e::::::::eeeeeeee   r:::::r             ,::::,      e::::::::eeeeeeee   u:::::::::::::::u           tt::::::::::::::t e::::::::eeeeeeee       a:::::aaaa::::::a m::::m   m::::m   m::::mo:::::::::::::::o   !!! 
E::::::::::::::::::::E s:::::::::::ss          tt:::::::::::tth:::::h     h:::::h  ee:::::::::::::e   r:::::r             ,::::,       ee:::::::::::::e    uu::::::::uu:::u             tt:::::::::::tt  ee:::::::::::::e        a::::::::::aa:::am::::m   m::::m   m::::m oo:::::::::::oo   !!:!!
EEEEEEEEEEEEEEEEEEEEEE  sssssssssss              ttttttttttt  hhhhhhh     hhhhhhh    eeeeeeeeeeeeee   rrrrrrr             ,:::,,         eeeeeeeeeeeeee      uuuuuuuu  uuuu               ttttttttttt      eeeeeeeeeeeeee         aaaaaaaaaa  aaaammmmmm   mmmmmm   mmmmmm   ooooooooooo      !!! 
                                                                                                                         ,:::,                                                                                                                                                                  
                                                                                                                         ,,,,                                                                                                                                                                   
                                                                                                                                                                                                                                                                 ( ˘ ³˘)♥                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                
          Força, guerreira 💖
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                
`}</code>
    </pre>
  );
}

export default Home;
